### ISSUE TITLE
really good stuff !

### ISSUE THREAD

**Issue by samxplogs** [Nem0oo/flipper-zero_ios-bluetooth-trigger#2]
not an issue but I wanted to say thanks and this is really nice application.
Did you thought about developping bunch of scripts/automation/bad usb or bluetooth for iOS devices ?

**Comment by Nem0oo** [comment]
Thanks :)
I have a bunch of ideas that I want to try out, for now I'm just having fun with it. I'm a fan of bad USB but I have really no use for it as the only computer I have access to is mine :p Maybe I'll use it to create some shortcuts in the future if I think of something :)
